weights: yolov5l.pt
cfg: ''
data: /home/mleeuwen/Deep learning Models/Total_bone_detector/yolov5/data/Coronal_BSv2_v5.yaml
hyp:
  lr0: 0.01054
  lrf: 0.1
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 2.972
  warmup_momentum: 0.8
  warmup_bias_lr: 0.09784
  box: 0.05405
  cls: 0.3
  cls_pw: 0.92567
  obj: 0.69917
  obj_pw: 0.975
  iou_t: 0.2
  anchor_t: 4.0
  fl_gamma: 0.0
  hsv_h: 0.0
  hsv_s: 0.0
  hsv_v: 0.0
  degrees: 0.0
  translate: 0.0
  scale: 0.0
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.0
  mosaic: 0.0
  mixup: 0.0
  copy_paste: 0.0
  anchors: 3.5275
epochs: 1000
batch_size: -1
imgsz: 672
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '1'
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: Coronal_BS_final
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 25
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/Coronal_BS_final2
